id: IC67F5767
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:10:36+00:00'
last_modified: '2022-06-07T16:55:10.446307+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30026
  title: འདན་མའི་ནས་རྫོང་ཕབ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    424E:
      image_group_id: I1KG17075
      title: ''
      total_pages: 130
      order: 1
      base_file: 424E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
