id: P003002
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:33:40.787892
source_metadata:
  id: bdr:W30026
  title: འདན་མའི་ནས་རྫོང་ཕབ་པ།
  author: ''
  volumes:
    195dd89ca5454ebb880290b70501faf9:
      image_group_id: I1KG17075
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
